server:
  port: 8080
spring:
  application:
    name: spring-cloud-gateway-service

  cloud:
    gateway:
      routes:
        - id: first-service
          uri: http://localhost:8081/
          predicates:
            - Path=/employee/**
        - id: second-service
          uri: http://localhost:8082/
          predicates:
            - Path=/consumer/**